export const LOAD_BOOKMARKS = 'LOAD_BOOKMARKS'
export const SORT_DATE_DESC = 'SORT_DATE_DESC'
export const SORT_DATE_ASC = 'SORT_DATE_ASC'
export const SPEC_CAT = 'SPEC_CAT'
export const SET_CATS = 'SET_CATS'
export const SET_CAT_MAX = 'SET_CAT_MAX'
export const RES_SPEC_CAT = 'RES_SPEC_CAT'